### ISSUE TITLE
Create uptest Github Action

### ISSUE THREAD

**Issue by ytsarev** [upbound/uptest#31]
### What problem are you facing?

Currently, we are configuring repetitive GHA workflows across the Configurations under test,e.g.

* https://github.com/upbound/platform-ref-gcp/blob/main/.github/workflows/e2e.yaml
* https://github.com/upbound/platform-ref-azure/pull/18
* https://github.com/upbound/platform-ref-aws/pull/82

See initial [contextual discussion](https://github.com/upbound/platform-ref-azure/pull/18#discussion_r998146115)

### How could Upbound help solve your problem?

Encapsulate uptest e2e testing logic into standalone [composite Github Action](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) or [reusable workflow](https://docs.github.com/en/actions/using-workflows/reusing-workflows)

**Comment by turkenh** [comment]
As part of this work, we should also switch to the new style of setting output as @ytsarev suggested [here](https://github.com/upbound/platform-ref-aws/pull/82/files#r998103618).

**Comment by turkenh** [comment]
FTR, it looks like reusable workflows are a better choice for us since they provide more functionality than the composite actions which we would need. More details on the difference can be found [here](https://dev.to/n3wt0n/composite-actions-vs-reusable-workflows-what-is-the-difference-github-actions-11kd).
