### ISSUE TITLE
Configure & enable renovate bot

### ISSUE THREAD

**Issue by ulucinar** [upbound/uptest#78]
As we are moving to reusable workflows for the provider repositories, we would like to configure and enable the renovate bot for uptest. We expect the renovate bot to update the common dependencies across the official provider repositories.

**Comment by turkenf** [comment]
While working on caller workflow PRs in provider terraform ([PR](https://github.com/upbound/provider-terraform/pull/107) for CI, [PR](https://github.com/upbound/provider-terraform/pull/110) for others), we encountered conflict because the [Update dependency golangci/golangci-lint to v1.51.2](https://github.com/upbound/provider-terraform/pull/118/files) and [Pin dependencies](https://github.com/upbound/provider-terraform/pull/94/files) PRs opened by renovate bot were merged. After that, our aim is to collect GitHub workflows in uptest repo for official providers. We want to make changes and updates on workflows only on reusable workflows in uptest.
So, we are waiting for the renovate bot we will add to up test to update the common dependencies in the official provider repositories.

**Comment by dverveiko** [comment]
@turkenf Renovate bot configuration for Uptest repo - https://github.com/upbound/uptest/pull/83
Changing in renovate bot configurations for OP:
AWS - https://github.com/upbound/provider-aws/pull/609
GCP - https://github.com/upbound/provider-gcp/pull/257
Azure - https://github.com/upbound/provider-azure/pull/410
AzureAD - https://github.com/upbound/provider-azuread/pull/38
Terraform - https://github.com/upbound/provider-terraform/pull/133 (Also in this PR I've downgraded golangci-lint version)

cc @ulucinar @sergenyalcin
